<?php
/**
 * @file
 * Make a menu or some other element on the page stick on top when you scroll
 * down
 */

/**
 * Implements hook_page_build().
 */
function stickynav_page_build(&$page) {
  global $theme;
  $config = Drupal::config('stickynav.settings');
  $enabled = $config->get('stickynav-enabled-' . $theme);
  $selector = $config->get('stickynav-selector-' . $theme);
  if ($enabled && trim($selector)) {
    $page['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => array(
        'stickynav' => array(
          'selector' => $selector,
        )
      ),
    );
    $page['#attached']['js'][] = drupal_get_path('module', 'stickynav') . '/js/stickynav.js';
    $page['#attached']['css'][] = drupal_get_path('module', 'stickynav') . '/css/stickynav.css';
  }
}

/**
 * Implements hook_permission().
 */
function stickynav_permission() {
  return array(
    'administer stickynav' => array(
      'title' => t('Administer Sticky Nav'),
      'description' => t('Permission to activate and manage Sticky Nav.'),
    ),
  );
}
